name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.0.11
  connectivity_plus: ^5.0.2
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.7
  flutter_typeahead: ^4.3.7
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^1.0.7
  image_picker_ios: ^0.8.5+6
  universal_html: ^2.0.8
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.1.2
  http: ^1.2.1
  pointer_interceptor: ^0.10.1
  phone_numbers_parser: ^8.2.1
  country_code_picker: ^3.0.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.4
  dotted_border: ^2.0.0+1
  share_plus: ^7.2.1
  expandable_bottom_sheet: ^1.1.1+1
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  flutter_facebook_auth: ^6.0.4
  flutter_animarker: ^3.2.0
  sign_in_with_apple: ^4.3.0
  intl: ^0.19.0
  just_the_tooltip: ^0.0.12
  flutter_slidable: ^3.0.0
  animated_flip_counter: ^0.2.5
  youtube_player_iframe: ^4.0.4
  card_swiper: ^3.0.1
  audioplayers: ^5.2.1
  firebase_crashlytics: ^3.5.7
  video_player: ^2.8.6
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html_core: ^0.14.12
  image: ^4.2.0
  smooth_page_indicator: ^1.1.0
  chewie: ^1.8.1
  location: ^7.0.0
  firebase_auth: ^4.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/map/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900